######################################################################
# Automatically generated by qmake (3.0) mié. may. 25 23:03:13 2016
######################################################################

TEMPLATE = app
TARGET = desktop
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
