######################################################################
# Automatically generated by qmake (3.0) dom. jun. 19 18:12:11 2016
######################################################################

TEMPLATE = lib
CONFIG += staticlib
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build

QT += network xml

DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/types.h

LIBS += -lqxmpp
