######################################################################
# Automatically generated by qmake (2.01a) s�b jun 4 23:04:36 2016
######################################################################

TEMPLATE = app
TARGET = sauron
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build

QT += network xml

DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
SOURCES += src/main.cpp \
    src/console.cpp

LIBS += -lqxmpp

HEADERS += \
    include/console.h
