######################################################################
# Automatically generated by qmake (3.0) mi�. may. 25 23:03:13 2016
######################################################################

TEMPLATE = app
TARGET = bot
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build

QT += core network xml

DEPENDPATH += . include src ../core
INCLUDEPATH += . include ../core/include

# Input
SOURCES += src/main.cpp \
    src/botmanager.cpp \
    src/storagemanager.cpp \
    src/attacker.cpp

HEADERS += \
    include/botmanager.h \
    include/storagemanager.h \
    include/global.h \
    include/attacker.h

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../core/release/ -lcore
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../core/debug/ -lcore
else:unix: LIBS += -L$$PWD/../core/ -lcore

unix|win32: LIBS += -lqxmpp
